---
- name: Run both the RHEL 6 STIG and RHEL 7 STIG Roles
  hosts: all
  become: yes

  vars:
    rhel6stig_update_all_packages: yes
    check_mode_warning:
      - "This was only an Ansible Check-Mode Run !"
      - "Examine the Recap Summary below for nodes that WOULD have been changed."

  tasks:

      # You can add "one-off" quick and dirty checks here (before the block of local_actions)
      # This will run on each node
    - name: Oneoff checks
      command: 
        warn: false
        argv:
          - rpm 
          -  "-Va"
            # This verifies packages (but reports on files in packages). 
            # It produces a list of changed files in stdout
      register: ONEOFF-001-RESULTS
      changed_when: true
      failed_when: false
            # only mark changed when stdout is non empty
      tags:
        - ONEOFF-001
            # Remedying this type of test is outside the scope of a POC. It probably means reinstalling any packages owning the files reported. Almost always there will be files reported.
            # Determining which files you expect to see here would aid in finding the right onese to validate.
 
            # Another new oneoff would be entered here before the when
      when: ansible_check_mode
      check_mode: no

    - name: latest RESULTS
      debug: var=ONEOFF-001-RESULTS
      run_once: true
      when: ansible_check_mode
      tags: ONEOFF-001

    - name: Block of local_action (reporting) tasks
      block:
        - name: create temporary file
          local_action: tempfile state=file suffix=.stig_check_report
          register: stig_temp
          changed_when: false

        - name: "Generate summary report from compliance check"
          local_action: "template src=hostvars.j2 dest={{stig_temp.path}} mode='a+r' backup=yes"
          changed_when: false

        - name: Echo tmpfile
          local_action:  debug var=stig_temp.path
          changed_when: false

        - name: cat report
          local_action: "command cat {{stig_temp.path}}"
          register: stig_report
          changed_when: false

        - name: show report
          local_action: debug var=stig_report.stdout
          changed_when: false
      run_once: True
      check_mode: no
      when: ansible_check_mode
      become: no
      tags: check-mode-tag
      # Tagged since we only run tagged items generally speaking with this playbook.
