- hosts: all
  become: yes

  vars:
    rhel6stig_update_all_packages: yes
#    rhel6stig_update_all_packages: no

  roles:
    - role: MindPointGroup.stig_rhel6
      rhel6stig_cat1: yes
      rhel6stig_cat2: yes
      rhel6stig_cat3: yes
      when:
          - ansible_os_family == 'RedHat'
          - ansible_distribution_major_version | version_compare('6', '=')

