---
- name: Run both the RHEL 6 STIG and RHEL 7 STIG Roles
  hosts: all
  become: yes

  vars:
    rhel6stig_update_all_packages: yes
    check_mode_warning:
      - "This was only an Ansible Check-Mode Run !"
      - "Examine the Recap Summary below for nodes that WOULD have been changed."

  roles:
    - role: CernerPOC.stig_rhel6
      rhel6stig_cat1: yes
      rhel6stig_cat2: yes
      rhel6stig_cat3: yes
      when:
          - ansible_os_family == 'RedHat'
          - not ansible_check_mode
          - ansible_distribution_major_version | version_compare('6', '=')

    - role: CernerPOC.RHEL7-STIG
      rhel7stig_cat1_patch: yes
      rhel7stig_cat2_patch: yes
      rhel7stig_cat3_patch: yes
      when:
          - ansible_os_family == 'RedHat'
          - ansible_distribution_major_version | version_compare('7', '=')
          - not ansible_check_mode

    - role: CernerPOC.stig_rhel6
      rhel6stig_cat1: yes
      rhel6stig_cat2: yes
      rhel6stig_cat3: yes
      when:
          - ansible_os_family == 'RedHat'
          - ansible_distribution_major_version | version_compare('6', '=')
          - ansible_check_mode

    - role: CernerPOC.RHEL7-STIG
      rhel7stig_cat1_patch: yes
      rhel7stig_cat2_patch: yes
      rhel7stig_cat3_patch: yes
      when:
          - ansible_os_family == 'RedHat'
          - ansible_distribution_major_version | version_compare('7', '=')
          - ansible_check_mode

  tasks:

      # You can add "one-off" quick and dirty checks here (before the block of local_actions)
      # This will run on each node
    - name: Oneoff checks
      command: rpm -Va
            # This verifies packages (but reports on files in packages). 
            # It produces a list of changed files in stdout
      register: ONEOFF-001-RELEASES
      changed_when: true
      failed_when: false
            # only mark changed when stdout is non empty
      tags:
        - ONEOFF-001
            # Remedying this type of test is outside the scope of a POC. It probably means reinstalling any packages owning the files reported. Almost always there will be files reported.
            # Determining which files you expect to see here would aid in finding the right onese to validate.
 
            # Another new oneoff would be entered here before the when
      when: ansible_check_mode
      check_mode: no
      tags: ONEOFF-001

    - name: latest RESULTS
      debug: var=ONEOFF-001-RELEASES
      run_once: true
      when: ansible_check_mode

    - name: Block of local_action (reporting) tasks
      block:
        - name: create temporary file
          local_action: tempfile state=file suffix=.stig_check_report
          register: stig_temp

        - name: "Generate summary report from compliance check"
          local_action: "template src=hostvars.j2 dest={{stig_temp.path}} mode='a+r' backup=yes"

        - name: Echo tmpfile
          local_action:  debug var=stig_temp.path

        - name: cat report
          local_action: "command cat {{stig_temp.path}}"
          register: stig_report

        - name: show report
          local_action: debug var=stig_report.stdout
      run_once: True
      check_mode: no
      when: ansible_check_mode
      become: no
      tags: check-mode-tag
      # Tagged since we only run tagged items generally speaking with this playbook.
