---
- name: Run both the RHEL 6 STIG and RHEL 7 STIG Roles
  hosts: all
  become: yes

  vars:
    rhel6stig_update_all_packages: yes
    check_mode_warning:
      - "This was only an Ansible Check-Mode Run !"
      - "Examine the Recap Summary below for nodes that WOULD have been changed."

  roles:
    - role: MindPointGroup.stig_rhel6
      rhel6stig_cat1: yes
      rhel6stig_cat2: yes
      rhel6stig_cat3: yes
      when:
          - ansible_os_family == 'RedHat'
          - not ansible_check_mode
          - ansible_distribution_major_version | version_compare('6', '=')

    - role: MindPointGroup.RHEL7-STIG
      rhel7stig_cat1_patch: yes
      rhel7stig_cat2_patch: yes
      rhel7stig_cat3_patch: yes
      when:
          - ansible_os_family == 'RedHat'
          - ansible_distribution_major_version | version_compare('7', '=')
          - not ansible_check_mode

    - role: MindPointGroup.stig_rhel6
      rhel6stig_cat1: yes
      rhel6stig_cat2: yes
      rhel6stig_cat3: yes
      when:
          - ansible_os_family == 'RedHat'
          - ansible_distribution_major_version | version_compare('6', '=')
          - ansible_check_mode


    - role: MindPointGroup.RHEL7-STIG
      rhel7stig_cat1_patch: yes
      rhel7stig_cat2_patch: yes
      rhel7stig_cat3_patch: yes
      when:
          - ansible_os_family == 'RedHat'
          - ansible_distribution_major_version | version_compare('7', '=')
          - ansible_check_mode

  tasks:
    - name: "Generate summary report from compliance check"
      local_action: template src=hostvars.j2 dest=/home/medberry/tmp/PLAY_OUTPUT owner=medberry group=medberry mode='a+r' backup=yes
      tags: check-mode-tag
# Tagged since we only run tagged items generally speaking with this playbook.
      run_once: True
      check_mode: no
      changed_when: False
      when: ansible_check_mode

