---
- name: Header
  hosts: localhost
  vars:
    rhel6stig_update_all_packages: yes
    check_mode_warning:
      - "This was only an Ansible Check-Mode Run !"
      - "Examine the PLAY RECAP below for nodes that WOULD have been changed."

  tasks:
    - name: Show Header
      debug:
        var: check_mode_warning
      changed_when: true
      tags: check-mode-tag
      when: ansible_check_mode

- name: Run both the RHEL 6 STIG and RHEL 7 STIG Roles
  hosts: all
  become: yes

  vars:
    rhel6stig_update_all_packages: yes
    check_mode_warning:
      - "This was only an Ansible Check-Mode Run !"
      - "Examine the Recap Summary below for nodes that WOULD have been changed."

  roles:
    - role: MindPointGroup.stig_rhel6
      rhel6stig_cat1: yes
      rhel6stig_cat2: yes
      rhel6stig_cat3: yes
      when:
          - ansible_os_family == 'RedHat'
          - not ansible_check_mode
          - ansible_distribution_major_version | version_compare('6', '=')
          # No environment changes

    - role: MindPointGroup.RHEL7-STIG
      rhel7stig_cat1_patch: yes
      rhel7stig_cat2_patch: yes
      rhel7stig_cat3_patch: yes
      when:
          - ansible_os_family == 'RedHat'
          - ansible_distribution_major_version | version_compare('7', '=')
          - not ansible_check_mode
          # No environment changes

    - role: MindPointGroup.stig_rhel6
      rhel6stig_cat1: yes
      rhel6stig_cat2: yes
      rhel6stig_cat3: yes
      when:
          - ansible_os_family == 'RedHat'
          - ansible_distribution_major_version | version_compare('6', '=')
          - ansible_check_mode
    - role: MindPointGroup.RHEL7-STIG
      rhel7stig_cat1_patch: yes
      rhel7stig_cat2_patch: yes
      rhel7stig_cat3_patch: yes
      when:
          - ansible_os_family == 'RedHat'
          - ansible_distribution_major_version | version_compare('7', '=')

  tasks:
    - name: tasks in main play
      local_action: template src=hostvars.j2 dest=/home/medberry/tmp/PLAY_OUTPUT owner=medberry group=medberry mode='a+r'
      tags: check-mode-tag
      run_once:
      ignore_errors:
      
#
#- name: Footer
#  hosts: localhost
#  vars:
#    rhel6stig_update_all_packages: yes
#    check_mode_warning:
#      - "This was only an Ansible Check-Mode Run !"
#      - "Examine the PLAY RECAP for nodes that WOULD have been changed."
#
#
#  tasks:
#    - name: Show Footer
#      debug:
#        var: check_mode_warning
#      changed_when: true
#      tags: check-mode-tag
#      when: ansible_check_mode
#
#    - name: hostvars
#      debug:
#        var: hostvars[0]
#      tags: check-mode-tag
#      changed_when: true
#      
#
#    - name: CHANGED
#      local_action: template src=template.j2 dest=output_file_from_template.out
#      tags: check-mode-tag
#      changed_when: true
#      register: template_results
#
#    - name: debug results
#      debug:
#        var: template_results
#      tags: check-mode-tag
#      changed_when: true
#
#    - name: create some file
#      local_action: template src=hostvars.j2 dest=/tmp/hostvars.out
#      tags: check-mode-tag
#      
